//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAutos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Auto
    {
        public int aut_id { get; set; }
        [DisplayName("PERSONA")]
        public Nullable<int> per_id { get; set; }
        [DisplayName("PLACA")]
        public string aut_placa { get; set; }
        [DisplayName("MODELO")]
        public string aut_modelo { get; set; }
        [DisplayName("COLOR")]
        public string aut_color { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
