//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAutos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Persona
    {
        public Persona()
        {
            this.Auto = new HashSet<Auto>();
        }
    
        public int per_id { get; set; }
        [DisplayName("NOMBRE")]
        public string per_nombre { get; set; }
        [DisplayName("EDAD")]
        public Nullable<int> per_edad { get; set; }
    
        public virtual ICollection<Auto> Auto { get; set; }
    }
}
